name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
      - name: cargo fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
      - name: Test (+nightly)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all
      - name: Build (+nightly)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release

  doctest-nightly:
    name: Doctests (+nightly)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    # Because we use nightly features for building docs,
    # using --all-features will fail without nightly toolchain.
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --all-targets

  coverage:
    name: Code Coverage (+nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.12.3'
          timeout: 300
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  clippy:
    name: Clippy (+nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings
